//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=safvialcentercorp.ddns.net;Initial Catalog=SAP;Persist Security Info=" +
            "True;User ID=sap;Password=sap1234")]
        public string SAP {
            get {
                return ((string)(this["SAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql5103.site4now.net;Initial Catalog=DB_A49549_safvialGuarico;Persist" +
            " Security Info=True;User ID=DB_A49549_safvialGuarico_admin;Password=s0p0rt3m;Mul" +
            "tipleActiveResultSets=True")]
        public string SafvialWeb {
            get {
                return ((string)(this["SafvialWeb"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Canal {
            get {
                return ((int)(this["Canal"]));
            }
            set {
                this["Canal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Sede {
            get {
                return ((int)(this["Sede"]));
            }
            set {
                this["Sede"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cobrador")]
        public string Tipo {
            get {
                return ((string)(this["Tipo"]));
            }
            set {
                this["Tipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("safvialcasetejacorp.ddns.net")]
        public string IP1 {
            get {
                return ((string)(this["IP1"]));
            }
            set {
                this["IP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("safvialcasetejacorp.ddns.net")]
        public string IP2 {
            get {
                return ((string)(this["IP2"]));
            }
            set {
                this["IP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("safvialcasetejacorp.ddns.net")]
        public string IP3 {
            get {
                return ((string)(this["IP3"]));
            }
            set {
                this["IP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("safvialhatoviejocorp.ddns.net")]
        public string IP4 {
            get {
                return ((string)(this["IP4"]));
            }
            set {
                this["IP4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAP")]
        public string dbo1 {
            get {
                return ((string)(this["dbo1"]));
            }
            set {
                this["dbo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SafvialPrepago")]
        public string dbo2 {
            get {
                return ((string)(this["dbo2"]));
            }
            set {
                this["dbo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SafvialWeb")]
        public string dbo3 {
            get {
                return ((string)(this["dbo3"]));
            }
            set {
                this["dbo3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAP")]
        public string dbo4 {
            get {
                return ((string)(this["dbo4"]));
            }
            set {
                this["dbo4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap")]
        public string User1 {
            get {
                return ((string)(this["User1"]));
            }
            set {
                this["User1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap")]
        public string User2 {
            get {
                return ((string)(this["User2"]));
            }
            set {
                this["User2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap")]
        public string User3 {
            get {
                return ((string)(this["User3"]));
            }
            set {
                this["User3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap")]
        public string User4 {
            get {
                return ((string)(this["User4"]));
            }
            set {
                this["User4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap1234")]
        public string Pass1 {
            get {
                return ((string)(this["Pass1"]));
            }
            set {
                this["Pass1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap1234")]
        public string Pass2 {
            get {
                return ((string)(this["Pass2"]));
            }
            set {
                this["Pass2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap1234")]
        public string Pass3 {
            get {
                return ((string)(this["Pass3"]));
            }
            set {
                this["Pass3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap1234")]
        public string Pass4 {
            get {
                return ((string)(this["Pass4"]));
            }
            set {
                this["Pass4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s0p0rt3m")]
        public string Master {
            get {
                return ((string)(this["Master"]));
            }
            set {
                this["Master"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("safvialcasetejacorp.ddns.net")]
        public string IP5 {
            get {
                return ((string)(this["IP5"]));
            }
            set {
                this["IP5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAP")]
        public string dbo5 {
            get {
                return ((string)(this["dbo5"]));
            }
            set {
                this["dbo5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap")]
        public string User5 {
            get {
                return ((string)(this["User5"]));
            }
            set {
                this["User5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sap1234")]
        public string Pass5 {
            get {
                return ((string)(this["Pass5"]));
            }
            set {
                this["Pass5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Arduino {
            get {
                return ((string)(this["Arduino"]));
            }
            set {
                this["Arduino"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=safvialhatoviejocorp.ddns.net;Initial Catalog=SafvialPrepago;Persist " +
            "Security Info=True;User ID=sap;Password=sap1234")]
        public string SAP2P {
            get {
                return ((string)(this["SAP2P"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=safvialhatoviejocorp.ddns.net;Initial Catalog=SafvialPrepago;Persist " +
            "Security Info=True;User ID=sap;Password=sap1234;Connect Timeout=2")]
        public string ConexionPSC {
            get {
                return ((string)(this["ConexionPSC"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Alexis\\Dropbox\\Carabobo\\SAP\\SAP\\bin")]
        public string Logo {
            get {
                return ((string)(this["Logo"]));
            }
            set {
                this["Logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Factura {
            get {
                return ((int)(this["Factura"]));
            }
            set {
                this["Factura"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=safvialcentercorp.ddns.net;Initial Catalog=SAP;Persist Security Info=" +
            "True;User ID=sap;Password=sap1234")]
        public string SAP2 {
            get {
                return ((string)(this["SAP2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=safvialcentercorp.ddns.net;Initial Catalog=SAP;Persist Security Info=" +
            "True;User ID=sap;Password=sap1234")]
        public string Sede1 {
            get {
                return ((string)(this["Sede1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/Recaudadores.SafvialWeb.Model.DbWeb.csdl|res://*/Recaudadores.SafvialWeb.Model.DbWeb.ssdl|res://*/Recaudadores.SafvialWeb.Model.DbWeb.msl;provider=System.Data.SqlClient;provider connection string=""data source=sql5103.site4now.net;initial catalog=DB_A49549_safvialGuarico;persist security info=True;user id=DB_A49549_safvialGuarico_admin;password=s0p0rt3m;MultipleActiveResultSets=True;App=EntityFramework""")]
        public string SafvialWebEntities {
            get {
                return ((string)(this["SafvialWebEntities"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=safvialcentercorp.ddns.net;Initial Catalog=SafvialPrepago;Persist Sec" +
            "urity Info=True;User ID=sap;Password=sap1234")]
        public string Prepagado {
            get {
                return ((string)(this["Prepagado"]));
            }
        }
    }
}
